apiVersion: apps/v1
kind: Deployment
metadata:
  name: getting-started
spec:
  replicas: 2
  selector:
    matchLabels:
      app: getting-started
  template:
    metadata:
      labels:
        app: getting-started
    spec:
      containers:
        - name: getting-started
          image: getting-started:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: getting-started-service
spec:
  type: NodePort
  selector:
    app: getting-started
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
